In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('/kaggle/input/heterogeneity-human-activity-recognition-dataset/Phones_gyroscope.csv')
df

,sample_id,Arrival_Time,Creation_Time,x,y,z,User,Model,Device,gt
0,0,1424696633909,1424696631914042029,0.013748,-0.000626,-0.023376,a,nexus4,nexus4_1,stand
1,1,1424696633909,1424696631919046912,0.014816,-0.001694,-0.022308,a,nexus4,nexus4_1,stand
2,2,1424696633918,1424696631924051794,0.015884,-0.001694,-0.021240,a,nexus4,nexus4_1,stand
3,3,1424696633919,1424696631929117712,0.016953,-0.003830,-0.020172,a,nexus4,nexus4_1,stand
4,4,1424696633928,1424696631934214148,0.015884,-0.007034,-0.020172,a,nexus4,nexus4_1,stand
...,...,...,...,...,...,...,...,...,...,...
13932627,11306,1424778269892,79199637493000,-0.046844,0.337667,0.134677,i,s3mini,s3mini_2,bike
13932628,11307,1424778269906,79199651618000,-0.117598,0.221777,0.131749,i,s3mini,s3mini_2,bike
13932629,11308,1424778269920,79199665927000,-0.177617,0.056115,0.095152,i,s3mini,s3mini_2,bike
13932630,11309,1424778269932,79199677489000,-0.195183,-0.124429,0.063191,i,s3mini,s3mini_2,bike
13932631,11310,1424778269953,79199698266000,-0.162002,-0.208846,0.043184,i,s3mini,s3mini_2,bike

In [3]:
df2 = pd.read_csv('/kaggle/input/heterogeneity-human-activity-recognition-dataset/Watch_gyroscope.csv')
df2

,sample_id,Arrival_Time,Creation_Time,x,y,z,User,Model,Device,gt
0,0,1424696638743,27920678496000,-0.162187,-0.022104,0.059655,a,gear,gear_1,stand
1,1,1424696638743,27920681926000,-0.183225,-0.061785,0.012517,a,gear,gear_1,stand
2,2,1424696638743,27920692031000,-0.180829,-0.108657,-0.036485,a,gear,gear_1,stand
3,3,1424696638743,27920701997000,-0.147805,-0.157925,-0.098537,a,gear,gear_1,stand
4,7,1424696638744,27920743068000,0.182160,-0.323574,-0.277235,a,gear,gear_1,stand
...,...,...,...,...,...,...,...,...,...,...
3205426,27417,1424778496411,205519488602851,0.062805,0.171570,0.093369,i,lgwatch,lgwatch_2,bike
3205427,27418,1424778496411,205519493577216,0.093781,0.133118,0.083755,i,lgwatch,lgwatch_2,bike
3205428,27419,1424778496411,205519498551581,0.105530,0.097870,0.058121,i,lgwatch,lgwatch_2,bike
3205429,27420,1424778496411,205519503556464,0.122620,0.083984,0.038895,i,lgwatch,lgwatch_2,bike
3205430,27421,1424778496411,205519508530829,0.150391,0.098938,0.050644,i,lgwatch,lgwatch_2,bike

In [4]:
df3 =pd.read_csv('/kaggle/input/heterogeneity-human-activity-recognition-dataset/Phones_gyroscope.csv')
df3

,sample_id,Arrival_Time,Creation_Time,x,y,z,User,Model,Device,gt
0,0,1424696633909,1424696631914042029,0.013748,-0.000626,-0.023376,a,nexus4,nexus4_1,stand
1,1,1424696633909,1424696631919046912,0.014816,-0.001694,-0.022308,a,nexus4,nexus4_1,stand
2,2,1424696633918,1424696631924051794,0.015884,-0.001694,-0.021240,a,nexus4,nexus4_1,stand
3,3,1424696633919,1424696631929117712,0.016953,-0.003830,-0.020172,a,nexus4,nexus4_1,stand
4,4,1424696633928,1424696631934214148,0.015884,-0.007034,-0.020172,a,nexus4,nexus4_1,stand
...,...,...,...,...,...,...,...,...,...,...
13932627,11306,1424778269892,79199637493000,-0.046844,0.337667,0.134677,i,s3mini,s3mini_2,bike
13932628,11307,1424778269906,79199651618000,-0.117598,0.221777,0.131749,i,s3mini,s3mini_2,bike
13932629,11308,1424778269920,79199665927000,-0.177617,0.056115,0.095152,i,s3mini,s3mini_2,bike
13932630,11309,1424778269932,79199677489000,-0.195183,-0.124429,0.063191,i,s3mini,s3mini_2,bike
13932631,11310,1424778269953,79199698266000,-0.162002,-0.208846,0.043184,i,s3mini,s3mini_2,bike

In [5]:
data = pd.concat([df,df3],ignore_index=True)
data

,sample_id,Arrival_Time,Creation_Time,x,y,z,User,Model,Device,gt
0,0,1424696633909,1424696631914042029,0.013748,-0.000626,-0.023376,a,nexus4,nexus4_1,stand
1,1,1424696633909,1424696631919046912,0.014816,-0.001694,-0.022308,a,nexus4,nexus4_1,stand
2,2,1424696633918,1424696631924051794,0.015884,-0.001694,-0.021240,a,nexus4,nexus4_1,stand
3,3,1424696633919,1424696631929117712,0.016953,-0.003830,-0.020172,a,nexus4,nexus4_1,stand
4,4,1424696633928,1424696631934214148,0.015884,-0.007034,-0.020172,a,nexus4,nexus4_1,stand
...,...,...,...,...,...,...,...,...,...,...
27865259,11306,1424778269892,79199637493000,-0.046844,0.337667,0.134677,i,s3mini,s3mini_2,bike
27865260,11307,1424778269906,79199651618000,-0.117598,0.221777,0.131749,i,s3mini,s3mini_2,bike
27865261,11308,1424778269920,79199665927000,-0.177617,0.056115,0.095152,i,s3mini,s3mini_2,bike
27865262,11309,1424778269932,79199677489000,-0.195183,-0.124429,0.063191,i,s3mini,s3mini_2,bike
27865263,11310,1424778269953,79199698266000,-0.162002,-0.208846,0.043184,i,s3mini,s3mini_2,bike

In [6]:
data.to_csv('phone.csv',index=False)

In [7]:
phone= pd.read_csv('/kaggle/working/phone.csv')

In [ ]:
simu

In [ ]:
simu['Model'].value_counts()

In [ ]:
simu['User'].value_counts()

In [ ]:
simu['Device'].value_counts()

In [ ]:
simu.head()

In [ ]:
def convert_string_interger(df):
    # dictionary to store data
    column_identifier={}
    
    for column in df.columns:
        if df[column].dtype == object:
            # Extract unique strings from the colun
            unique_strings = df[column].unique()
            # crrate dictionary mapping
            string_identifier = {string: i for i, string in enumerate(unique_strings)}
            
            # store mapping to the dictionary
            column_identifier [column] =string_identifier
            # mapp to dataframe
            df[column] =df[column].apply(lambda x: string_identifier.get(x,float('nan')))
    return df, column_identifier

In [95]:
%%writefile human.py

import logging
import subprocess
import os
import yaml
import datetime
import gc
import re
import pandas as pd


# read file
def read_file(filepath):
    with open (filepath, 'r') as file:
        return yaml.safe_load(file)
            
# Converts string data to numerical  and stores it to dictionary
def convert_string_interger(df):
    # dictionary to store data
    column_identifier={}
    
    for column in df.columns:
        if df[column].dtype == object:
            # Extract unique strings from the colun
            unique_strings = df[column].unique()
            # crrate dictionary mapping
            string_identifier = {string: i for i, string in enumerate(unique_strings)}
            
            # store mapping to the dictionary
            column_identifier [column] =string_identifier
            
            # mapp to dataframe
            df[column] =df[column].apply(lambda x: string_identifier.get(x,float('nan')))
            
    return df
def get_file_size(filepath):
    size = os.path.getsize(filepath)
    return size/10224
def filedata(df,filepath):
    size = get_file_size(filepath)
    keys = ['Columns', 'rows','File size in Mb']
    N_values = [df.columns, len(df), size]
    dicto = dict(zip(keys, N_values))
    return dicto
def write_to_pipe_separated_gzip(df, filepath):
    df.to_csv(filepath, sep='|', index=False, compression='gzip')

Overwriting human.py

In [94]:
import os
def get_file_size(filepath):
    size = os.path.getsize(filepath)
    return size /(1024*10124)
p = get_file_size("/kaggle/working/phone.csv")
p

257.8516188327242

In [85]:
def filedata(df):
    keys = ['Columns', 'rows']
    N_values = [df.columns, len(df)]
    dicto = dict(zip(keys, N_values))
    return dicto

In [86]:
r = filedata(df)

In [87]:
r

{'Columns': Index(['sample_id', 'Arrival_Time', 'Creation_Time', 'x', 'y', 'z', 'User',
        'Model', 'Device', 'gt'],
       dtype='object'),
 'rows': 13932632}

In [96]:
%%writefile file.yaml
file_type: csv
dataset_name: phone_file
file_name: phone
table_name: edsurv
skip_leading_rows: 1
columns:
  - Index
  - Arrival_Time
  - Creation_Time
  - x
  - y
  - z
  - User
  - Model
  - Device
  - gt

Overwriting file.yaml

In [97]:
import sys
sys.path.append('/kaggle/working/')
import human as util

In [98]:
import importlib
#importlib.reload(human)
importlib.reload(util)

In [99]:
import sys
sys.path.append('/kaggle/working/')
import human as util
config_data = util.read_file("/kaggle/working/file.yaml")

In [100]:
config_data['file_type']

'csv'

In [45]:
config_data

{'file_type': 'csv',
 'dataset_name': 'phone_file',
 'file_name': 'phone',
 'table_name': 'edsurv',
 'skip_leading_rows': 1,
 'columns': ['Index',
  'Arrival_Time',
  'Creation_Time',
  'x',
  'y',
  'z',
  'User',
  'Model',
  'Device',
  'gt']}

In [46]:
file_type = config_data['file_type']
source_file = './'+ config_data['file_name'] + f'.{file_type}'
dd = pd.read_csv(source_file)

## convert object data type to interger

In [47]:
util.convert_string_interger(df=dd)

,sample_id,Arrival_Time,Creation_Time,x,y,z,User,Model,Device,gt
0,0,1424696633909,1424696631914042029,0.013748,-0.000626,-0.023376,0,0,0,0
1,1,1424696633909,1424696631919046912,0.014816,-0.001694,-0.022308,0,0,0,0
2,2,1424696633918,1424696631924051794,0.015884,-0.001694,-0.021240,0,0,0,0
3,3,1424696633919,1424696631929117712,0.016953,-0.003830,-0.020172,0,0,0,0
4,4,1424696633928,1424696631934214148,0.015884,-0.007034,-0.020172,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...
27865259,11306,1424778269892,79199637493000,-0.046844,0.337667,0.134677,8,2,5,6
27865260,11307,1424778269906,79199651618000,-0.117598,0.221777,0.131749,8,2,5,6
27865261,11308,1424778269920,79199665927000,-0.177617,0.056115,0.095152,8,2,5,6
27865262,11309,1424778269932,79199677489000,-0.195183,-0.124429,0.063191,8,2,5,6
27865263,11310,1424778269953,79199698266000,-0.162002,-0.208846,0.043184,8,2,5,6

In [79]:
util.write_to_pipe_separated_gzip(df, 'output_file.csv.gz')

In [101]:
util.filedata(dd,'/kaggle/working/phone.csv')

{'Columns': Index(['sample_id', 'Arrival_Time', 'Creation_Time', 'x', 'y', 'z', 'User',
        'Model', 'Device', 'gt'],
       dtype='object'),
 'rows': 27865264,
 'File size in Mb': 261457.5062597809}